### ISSUE TITLE
SQL Tables?

### ISSUE THREAD

**Issue by iTrustmaster** [Larsklopstra/Bootstrap-4-PDO-Forum#1]
Please share sql tables

**Comment by Larsklopstra** [comment]
Sure, I totally forgot that! I'll include the SQL export with the next **update**.

**Comment by darrovanlier** [comment]
gay

**Comment by darrovanlier** [comment]
you're such a loser

**Comment by darrovanlier** [comment]
@iTrustmaster go learn yourself cunt

**Comment by darrovanlier** [comment]
@iTrustmaster it aint that hard, Mike

**Comment by darrovanlier** [comment]
@iTrustmaster  Var12
